apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: sammirsharifi/node-url-shortener
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: server
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: server
            - name: API_KEY
              valueFrom:
                  secretKeyRef:
                    name: server
                    key: .API_KEY
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: .password
                  name: redis
          ports:
            - containerPort: 80
              name: server-port
          volumeMounts:
            - name: server
              mountPath: /app/config
      volumes:
        - name: server
          configMap:
            name: server
            items:
              - key: production-config
                path: production.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: server-port
      nodePort: 30000
